using System.CodeDom;
using System.CodeDom.Compiler;
using System.Linq;

namespace SolarSharp.Hardwire.Languages
{
    /// <summary>
    /// Represents a VB.NET-specific implementation of the hardwire code generation language.
    /// Provides methods and configurations for generating VB.NET code constructs.
    /// </summary>
    public class VbNetHardwireCodeGenerationLanguage : HardwireCodeGenerationLanguage
    {
        /// <inheritdoc />
        public override string Name
        {
            get { return "VB.NET"; }
        }

        /// <inheritdoc />
        public override CodeDomProvider CodeDomProvider { get; } =
            CodeDomProvider.CreateProvider("VisualBasic");

        /// <inheritdoc />
        public override CodeExpression UnaryPlus(CodeExpression arg)
        {
            return SnippetExpression("+{0}", arg);
        }

        /// <inheritdoc />
        public override CodeExpression UnaryNegation(CodeExpression arg)
        {
            return SnippetExpression("-{0}", arg);
        }

        /// <inheritdoc />
        public override CodeExpression UnaryLogicalNot(CodeExpression arg)
        {
            return SnippetExpression("Not {0}", arg);
        }

        /// <inheritdoc />
        public override CodeExpression UnaryOneComplement(CodeExpression arg)
        {
            return SnippetExpression("Not {0}", arg);
        }

        /// <inheritdoc />
        public override CodeExpression BinaryXor(CodeExpression arg1, CodeExpression arg2)
        {
            return SnippetExpression("{0} Xor {1}", arg1, arg2);
        }

        /// <inheritdoc />
        public override CodeExpression UnaryIncrement(CodeExpression arg)
        {
            // VB.NET doesn't have ++ operator, use assignment
            return SnippetExpression("{0} + 1", arg);
        }

        /// <inheritdoc />
        public override CodeExpression UnaryDecrement(CodeExpression arg)
        {
            // VB.NET doesn't have -- operator, use assignment
            return SnippetExpression("{0} - 1", arg);
        }

        /// <inheritdoc />
        public override string[] GetInitialComment()
        {
            return new[]
            {
                "' This file was generated by SolarSharp hardwire",
                "' Do not modify this file manually",
            };
        }

        /// <inheritdoc />
        public override CodeExpression CreateMultidimensionalArray(
            string type,
            CodeExpression[] args
        )
        {
            // In VB.NET, array dimensions are upper bounds, not sizes
            var dimensionExpressions = args.Select(e => SnippetExpression("{0} - 1", e)).ToArray();

            var idxexp = new CodeSnippetExpression(
                string.Join(", ", dimensionExpressions.Select(e => ExpressionToString(e)))
            );

            return new CodeArrayCreateExpression(type, idxexp);
        }
    }
}
