<Project>
    <Sdk Name="DotNet.ReproducibleBuilds.Isolated" Version="1.2.25"/>
    <PropertyGroup>
        <!-- Force clean before build for test projects -->
        <CleanOnTestRun Condition="'$(IsTestProject)' == 'true'">true</CleanOnTestRun>
        <!-- Strong name signing for identity only -->
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)signing/open-signing-key.snk</AssemblyOriginatorKeyFile>
    </PropertyGroup>
    <ItemGroup>
        <!-- Reproducible Builds -->
        <PackageReference Include="DotNet.ReproducibleBuilds" Version="1.2.25" PrivateAssets="All"/>
    </ItemGroup>
</Project>
