#nullable enable

using System;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using CSharpFunctionalExtensions;
using SolarSharp.Interpreter.Execution;
using SolarSharp.Interpreter.Security.Auditing;
using SolarSharp.Interpreter.Security.Events;
using SolarSharp.Interpreter.Security.Manifests;

namespace SolarSharp.Interpreter.Security.Aggregates
{
    /// <summary>
    /// Domain aggregate for security policy lifecycle management using event-driven design
    /// </summary>
    public sealed class SecurityPolicyAggregate
    {
        /// <summary>
        /// Unique identifier for this policy aggregate
        /// </summary>
        public SecurityPolicyId Id { get; }

        /// <summary>
        /// Immutable collection of security policies managed by this aggregate
        /// </summary>
        public ImmutableDictionary<string, SecurityPolicy> Policies { get; private set; } =
            ImmutableDictionary<string, SecurityPolicy>.Empty;

        /// <summary>
        /// Immutable array of domain events generated by this aggregate
        /// </summary>
        public ImmutableArray<SecurityAuditEvent> Events { get; private set; } =
            ImmutableArray<SecurityAuditEvent>.Empty;

        /// <summary>
        /// Event publisher for reactive updates
        /// </summary>
        private readonly IEventPublisher? _eventPublisher;

        /// <summary>
        /// Version number for optimistic concurrency control
        /// </summary>
        public long Version { get; private set; }

        /// <summary>
        /// Creates a new security policy aggregate
        /// </summary>
        /// <param name="id">Unique identifier for the aggregate</param>
        /// <param name="eventPublisher">Optional event publisher for reactive updates</param>
        public SecurityPolicyAggregate(SecurityPolicyId id, IEventPublisher? eventPublisher = null)
        {
            Id = id;
            _eventPublisher = eventPublisher;
        }

        /// <summary>
        /// Resolves the effective security policy for an execution context using pure functional composition
        /// </summary>
        /// <param name="context">The execution context to resolve policy for</param>
        /// <param name="correlationId">Optional correlation ID for tracing</param>
        /// <param name="cancellationToken">Cancellation token for async operations</param>
        /// <returns>Result containing the resolved policy or error</returns>
        public async Task<Result<SecurityPolicy, PolicyResolutionError>> ResolvePolicyAsync(
            LuaExecutionContext context,
            string? correlationId = null,
            CancellationToken cancellationToken = default
        )
        {
            // Generate policy resolution started event
            var startedEvent = new PolicyResolutionStartedEvent(
                Id.Value,
                context.SourceFile,
                context.Identity.HasValue ? context.Identity.Value.Name : "Unknown",
                correlationId
            );

            await PublishEventAsync(startedEvent, correlationId, cancellationToken);

            try
            {
                var result = await ResolvePolicyInternal(context);

                // Generate policy resolution completed event
                var completedEvent = new PolicyResolutionCompletedEvent(
                    Id.Value,
                    context.SourceFile,
                    result.IsSuccess ? result.Value.Name.GetValueOrDefault("Unknown") : "Failed",
                    correlationId
                );

                await PublishEventAsync(completedEvent, correlationId, cancellationToken);

                return result;
            }
            catch (Exception ex)
            {
                // Generate policy resolution failed event
                var failedEvent = new PolicyResolutionFailedEvent(
                    Id.Value,
                    context.SourceFile,
                    ex.Message,
                    correlationId
                );

                await PublishEventAsync(failedEvent, correlationId, cancellationToken);

                return Result.Failure<SecurityPolicy, PolicyResolutionError>(
                    new PolicyResolutionError($"Policy resolution failed: {ex.Message}", ex)
                );
            }
        }

        /// <summary>
        /// Internal policy resolution using functional composition
        /// </summary>
        private Task<Result<SecurityPolicy, PolicyResolutionError>> ResolvePolicyInternal(
            LuaExecutionContext context
        )
        {
            return Task.FromResult(
                GetSignatureBasedPolicy(context)
                    .Match(
                        policy => Result.Success<SecurityPolicy, PolicyResolutionError>(policy),
                        () =>
                            GetPathBasedPolicy(context)
                                .Match(
                                    policy =>
                                        Result.Success<SecurityPolicy, PolicyResolutionError>(
                                            policy
                                        ),
                                    () =>
                                        GetFallbackPolicy()
                                            .Match(
                                                policy =>
                                                    Result.Success<
                                                        SecurityPolicy,
                                                        PolicyResolutionError
                                                    >(policy),
                                                () =>
                                                    Result.Failure<
                                                        SecurityPolicy,
                                                        PolicyResolutionError
                                                    >(
                                                        new PolicyResolutionError(
                                                            "No applicable policy found"
                                                        )
                                                    )
                                            )
                                )
                    )
            );
        }

        /// <summary>
        /// Gets signature-based policy using functional composition
        /// </summary>
        private Maybe<SecurityPolicy> GetSignatureBasedPolicy(LuaExecutionContext context)
        {
            return context
                .Identity.Map(identity => CertificateManager.TokenToHex(identity.PublicKeyToken))
                .Bind(token =>
                    Policies.TryGetValue(token, out var policy)
                        ? Maybe<SecurityPolicy>.From(policy.WithName($"Signature[{token}]"))
                        : Maybe<SecurityPolicy>.None
                );
        }

        /// <summary>
        /// Gets path-based policy using functional composition and pattern matching
        /// </summary>
        private Maybe<SecurityPolicy> GetPathBasedPolicy(LuaExecutionContext context)
        {
            if (string.IsNullOrEmpty(context.SourceFile))
                return Maybe<SecurityPolicy>.None;

            // Find most specific path pattern match
            var matchingPolicy = Policies
                .Where(kvp => IsPathMatch(context.SourceFile, kvp.Key))
                .OrderByDescending(kvp => kvp.Key.Length) // Most specific first
                .Select(kvp => kvp.Value.WithName($"Path[{kvp.Key}]"))
                .FirstOrDefault();

            return matchingPolicy != null
                ? Maybe<SecurityPolicy>.From(matchingPolicy)
                : Maybe<SecurityPolicy>.None;
        }

        /// <summary>
        /// Gets fallback policy
        /// </summary>
        private Maybe<SecurityPolicy> GetFallbackPolicy()
        {
            return Policies.TryGetValue("", out var fallbackPolicy)
                ? Maybe<SecurityPolicy>.From(fallbackPolicy.WithName("Fallback"))
                : Maybe<SecurityPolicy>.None;
        }

        /// <summary>
        /// Simple path pattern matching (can be enhanced with proper glob patterns)
        /// </summary>
        private static bool IsPathMatch(string filePath, string pattern)
        {
            if (pattern is "*" or "**/*")
                return true;

            if (pattern.EndsWith("*"))
            {
                var prefix = pattern[..^1];
                return filePath.StartsWith(prefix);
            }

            return filePath == pattern;
        }

        /// <summary>
        /// Adds a new security policy to the aggregate using immutable updates
        /// </summary>
        /// <param name="key">Policy key (signature token, path pattern, etc.)</param>
        /// <param name="policy">The security policy to add</param>
        /// <param name="correlationId">Optional correlation ID for tracing</param>
        /// <param name="cancellationToken">Cancellation token for async operations</param>
        /// <returns>Result indicating success or failure</returns>
        public async Task<UnitResult<PolicyManagementError>> AddPolicyAsync(
            string key,
            SecurityPolicy policy,
            string? correlationId = null,
            CancellationToken cancellationToken = default
        )
        {
            try
            {
                // Immutable update
                Policies = Policies.SetItem(key, policy);
                Version++;

                // Generate policy added event
                var addedEvent = new PolicyAddedEvent(
                    Id.Value,
                    key,
                    policy.Name.GetValueOrDefault("Unknown"),
                    correlationId
                );

                await PublishEventAsync(addedEvent, correlationId, cancellationToken);

                return UnitResult.Success<PolicyManagementError>();
            }
            catch (Exception ex)
            {
                return UnitResult.Failure<PolicyManagementError>(
                    new PolicyManagementError($"Failed to add policy: {ex.Message}", ex)
                );
            }
        }

        /// <summary>
        /// Removes a security policy from the aggregate using immutable updates
        /// </summary>
        /// <param name="key">Policy key to remove</param>
        /// <param name="correlationId">Optional correlation ID for tracing</param>
        /// <param name="cancellationToken">Cancellation token for async operations</param>
        /// <returns>Result indicating success or failure</returns>
        public async Task<UnitResult<PolicyManagementError>> RemovePolicyAsync(
            string key,
            string? correlationId = null,
            CancellationToken cancellationToken = default
        )
        {
            try
            {
                if (!Policies.ContainsKey(key))
                {
                    return UnitResult.Failure<PolicyManagementError>(
                        new PolicyManagementError($"Policy with key '{key}' not found")
                    );
                }

                // Immutable update
                Policies = Policies.Remove(key);
                Version++;

                // Generate policy removed event
                var removedEvent = new PolicyRemovedEvent(Id.Value, key, correlationId);

                await PublishEventAsync(removedEvent, correlationId, cancellationToken);

                return UnitResult.Success<PolicyManagementError>();
            }
            catch (Exception ex)
            {
                return UnitResult.Failure<PolicyManagementError>(
                    new PolicyManagementError($"Failed to remove policy: {ex.Message}", ex)
                );
            }
        }

        /// <summary>
        /// Applies manifest policies by creating a new aggregate with intersected policies
        /// </summary>
        /// <param name="manifest">The manifest containing additional policies</param>
        /// <param name="correlationId">Optional correlation ID for tracing</param>
        /// <param name="cancellationToken">Cancellation token for async operations</param>
        /// <returns>Result containing new aggregate with manifest policies applied</returns>
        public async Task<
            Result<SecurityPolicyAggregate, PolicyManagementError>
        > WithManifestPoliciesAsync(
            LoadedManifest manifest,
            string? correlationId = null,
            CancellationToken cancellationToken = default
        )
        {
            try
            {
                var newAggregate = new SecurityPolicyAggregate(Id, _eventPublisher)
                {
                    Policies = Policies,
                    Version = Version + 1,
                };

                // TODO: V2.0 - Extract policies from signed content blocks
                // For now, skip policy application from manifests

                // Generate manifest policies applied event
                var appliedEvent = new ManifestPoliciesAppliedEvent(
                    Id.Value,
                    manifest.Manifest.GetAllPackages().FirstOrDefault().Package?.Metadata?.Name
                        ?? "Unknown",
                    0, // TODO: Count policies from signed content blocks
                    correlationId
                );

                await PublishEventAsync(appliedEvent, correlationId, cancellationToken);

                return Result.Success<SecurityPolicyAggregate, PolicyManagementError>(newAggregate);
            }
            catch (Exception ex)
            {
                return Result.Failure<SecurityPolicyAggregate, PolicyManagementError>(
                    new PolicyManagementError(
                        $"Failed to apply manifest policies: {ex.Message}",
                        ex
                    )
                );
            }
        }

        /// <summary>
        /// Publishes an event through the event publisher if available
        /// </summary>
        private async Task PublishEventAsync(
            SecurityAuditEvent auditEvent,
            string? correlationId,
            CancellationToken cancellationToken
        )
        {
            Events = Events.Add(auditEvent);

            if (_eventPublisher != null)
            {
                await _eventPublisher.PublishAsync(auditEvent, correlationId, cancellationToken);
            }
        }
    }

    /// <summary>
    /// Value object representing a security policy aggregate identifier
    /// </summary>
    public sealed record SecurityPolicyId
    {
        /// <summary>
        /// The unique identifier value
        /// </summary>
        public string Value { get; }

        /// <summary>
        /// Creates a new security policy ID
        /// </summary>
        /// <param name="value">The unique identifier value</param>
        public SecurityPolicyId(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
                throw new ArgumentException(
                    "Security policy ID cannot be null or empty",
                    nameof(value)
                );

            Value = value;
        }

        /// <summary>
        /// Creates a new random security policy ID
        /// </summary>
        public static SecurityPolicyId NewId() => new(Guid.NewGuid().ToString());

        /// <summary>
        /// Implicit conversion from string
        /// </summary>
        public static implicit operator SecurityPolicyId(string value) => new(value);

        /// <summary>
        /// Implicit conversion to string
        /// </summary>
        public static implicit operator string(SecurityPolicyId id) => id.Value;
    }

    /// <summary>
    /// Error type for policy management operations
    /// </summary>
    public sealed class PolicyManagementError
    {
        /// <summary>
        /// Error message describing the failure
        /// </summary>
        public string Message { get; init; } = string.Empty;

        /// <summary>
        /// Original exception that caused the failure, if any
        /// </summary>
        public Exception? Exception { get; init; }

        /// <summary>
        /// Timestamp when the error occurred
        /// </summary>
        public DateTime Timestamp { get; init; } = DateTime.UtcNow;

        /// <summary>
        /// Creates a new policy management error
        /// </summary>
        public PolicyManagementError(string message, Exception? exception = null)
        {
            Message = message;
            Exception = exception;
        }
    }

    // Domain Events for SecurityPolicyAggregate

    /// <summary>
    /// Event raised when policy resolution starts
    /// </summary>
    public sealed record PolicyResolutionStartedEvent : SecurityAuditEvent
    {
        public string SourceFile { get; init; } = string.Empty;
        public string ScriptName { get; init; } = string.Empty;

        public PolicyResolutionStartedEvent()
            : base(SecurityEventType.PolicyResolution)
        {
            Success = true;
            Operation = "policy_resolution_started";
        }

        public PolicyResolutionStartedEvent(
            string aggregateId,
            string sourceFile,
            string scriptName,
            string? correlationId = null
        )
            : this()
        {
            ScriptId = aggregateId;
            SourceFile = sourceFile;
            ScriptName = scriptName;

            if (correlationId != null)
                Metadata = Metadata.Add("correlation_id", correlationId);
        }
    }

    /// <summary>
    /// Event raised when policy resolution completes successfully
    /// </summary>
    public sealed record PolicyResolutionCompletedEvent : SecurityAuditEvent
    {
        public string SourceFile { get; init; } = string.Empty;
        public string ResolvedPolicyName { get; init; } = string.Empty;

        public PolicyResolutionCompletedEvent()
            : base(SecurityEventType.PolicyResolution)
        {
            Success = true;
            Operation = "policy_resolution_completed";
        }

        public PolicyResolutionCompletedEvent(
            string aggregateId,
            string sourceFile,
            string resolvedPolicyName,
            string? correlationId = null
        )
            : this()
        {
            ScriptId = aggregateId;
            SourceFile = sourceFile;
            ResolvedPolicyName = resolvedPolicyName;

            if (correlationId != null)
                Metadata = Metadata.Add("correlation_id", correlationId);
        }
    }

    /// <summary>
    /// Event raised when policy resolution fails
    /// </summary>
    public sealed record PolicyResolutionFailedEvent : SecurityAuditEvent
    {
        public string SourceFile { get; init; } = string.Empty;
        public string FailureReason { get; init; } = string.Empty;

        public PolicyResolutionFailedEvent()
            : base(SecurityEventType.PolicyResolution)
        {
            Success = false;
            Operation = "policy_resolution_failed";
        }

        public PolicyResolutionFailedEvent(
            string aggregateId,
            string sourceFile,
            string failureReason,
            string? correlationId = null
        )
            : this()
        {
            ScriptId = aggregateId;
            SourceFile = sourceFile;
            FailureReason = failureReason;
            ErrorMessage = failureReason;

            if (correlationId != null)
                Metadata = Metadata.Add("correlation_id", correlationId);
        }
    }

    /// <summary>
    /// Event raised when a policy is added to the aggregate
    /// </summary>
    public sealed record PolicyAddedEvent : SecurityAuditEvent
    {
        public string PolicyKey { get; init; } = string.Empty;
        public string PolicyName { get; init; } = string.Empty;

        public PolicyAddedEvent()
            : base(SecurityEventType.PolicyManagement)
        {
            Success = true;
            Operation = "policy_added";
        }

        public PolicyAddedEvent(
            string aggregateId,
            string policyKey,
            string policyName,
            string? correlationId = null
        )
            : this()
        {
            ScriptId = aggregateId;
            PolicyKey = policyKey;
            PolicyName = policyName;

            if (correlationId != null)
                Metadata = Metadata.Add("correlation_id", correlationId);
        }
    }

    /// <summary>
    /// Event raised when a policy is removed from the aggregate
    /// </summary>
    public sealed record PolicyRemovedEvent : SecurityAuditEvent
    {
        public string PolicyKey { get; init; } = string.Empty;

        public PolicyRemovedEvent()
            : base(SecurityEventType.PolicyManagement)
        {
            Success = true;
            Operation = "policy_removed";
        }

        public PolicyRemovedEvent(
            string aggregateId,
            string policyKey,
            string? correlationId = null
        )
            : this()
        {
            ScriptId = aggregateId;
            PolicyKey = policyKey;

            if (correlationId != null)
                Metadata = Metadata.Add("correlation_id", correlationId);
        }
    }

    /// <summary>
    /// Event raised when manifest policies are applied to the aggregate
    /// </summary>
    public sealed record ManifestPoliciesAppliedEvent : SecurityAuditEvent
    {
        public string ManifestName { get; init; } = string.Empty;
        public int PolicyCount { get; init; }

        public ManifestPoliciesAppliedEvent()
            : base(SecurityEventType.ManifestValidation)
        {
            Success = true;
            Operation = "manifest_policies_applied";
        }

        public ManifestPoliciesAppliedEvent(
            string aggregateId,
            string manifestName,
            int policyCount,
            string? correlationId = null
        )
            : this()
        {
            ScriptId = aggregateId;
            ManifestName = manifestName;
            PolicyCount = policyCount;

            if (correlationId != null)
                Metadata = Metadata.Add("correlation_id", correlationId);
        }
    }
}
