// <auto-generated />
#pragma warning disable

#if NETSTANDARD2_0 || NETFRAMEWORK || NETCOREAPP2X

namespace System.Diagnostics.CodeAnalysis
{
    using Targets = AttributeTargets;

    /// <summary>
    ///   Specifies that <see langword="null"/> is allowed as an input even if the
    ///   corresponding type disallows it.
    /// </summary>
    [ExcludeFromCodeCoverage]
    [DebuggerNonUserCode]
    [AttributeUsage(validOn: Targets.Field | Targets.Parameter | Targets.Property)]
    internal sealed class AllowNullAttribute : Attribute { }

    /// <summary>
    ///   Specifies that an output may be <see langword="null"/> even if the
    ///   corresponding type disallows it.
    /// </summary>
    [ExcludeFromCodeCoverage]
    [DebuggerNonUserCode]
    [AttributeUsage(validOn: Targets.Field | Targets.Parameter | Targets.Property | Targets.ReturnValue)]
    internal sealed class MaybeNullAttribute : Attribute { }
}

#endif